language: node_js
node_js:
  - "0.12"
install:
    - npm install
after_script:
    - NODE_ENV=test
    - istanbul cover ./node_modules/mocha/bin/_mocha test/todoapp.js
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - rm -rf ./coverage
deploy:
  provider: heroku
  api_key:
    secure: 714128d4-8955-409d-9d30-5a79ecfe1d6c
  app: pi7-todoapp
  on:
    repo: gabrielcyrino/ToDo-app
